name: flutter_offline
description: A tidy utility to handle offline/online connectivity like a Boss.
version: 0.2.4+2
author: Jeremiah Ogbomo <jeremiahogbomo@gmail.com>
homepage: https://github.com/jogboms/flutter_offline

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.4.0
