name: flutter_offline
description: A tidy utility to handle offline/online connectivity like a Boss.
version: 2.0.0
homepage: https://github.com/jogboms/flutter_offline

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity: ^3.0.2
  wifi_info_flutter: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
