name: flutter_offline
description: A tidy utility to handle offline/online connectivity like a Boss.
version: 3.0.0
homepage: https://github.com/jogboms/flutter_offline

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^4.0.1
  network_info_plus: ^4.0.1

dev_dependencies:
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
